name: matrix
on: push
jobs:
  build:
    strategy:
      matrix: 
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps: 
      - name: get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Insall dependencies
        run: npm ci
      - name: bild project
        run: npm run build
      

